[package]
name = "graph-codegen"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"

[dependencies]
serde = { version = "1.0.110", features = ["derive", "rc"] }
serde_json = "1.0.53"
serde_yaml = "0.8.9"
serde_derive = "^1.0"
toml = "0.5"
from_as = { git = "https://github.com/sreeise/from_as" }
regex = "1"
Inflector = "0.11.4"
url = "2.1.1"
reqwest = { version = "0.10", features = ["json", "blocking", "stream"] }
