[package]
name = "http-client"
version = "0.1.0"
authors = ["Sean Reeise"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json", "blocking"] }
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
handlebars = "3.0.1"